export const countryList = [
  { name: ["Switzerland", "Suisse", "Schweiz", "Svizzera"], code: "CH" },
  { name: ["Afghanistan", "Afghanistan", "Afghanistan", "Afghanistan"], code: "AF" },
  { name: ["Åland Islands", "Iles Aland", "Åland-Inseln", "Isole Aland"], code: "AX" },
  { name: ["Albania", "Albanie", "Albanien", "Albania"], code: "AL" },
  { name: ["Algeria", "Algérie", "Algerien", "Algeria"], code: "DZ" },
  { name: ["American Samoa", "Samoa Américaines", "Amerikanischen Samoa-Inseln", "Samoa americane"], code: "AS" },
  { name: ["Andorra", "Andorre", "Andorra", "Andorra"], code: "AD" },
  { name: ["Angola", "Angola", "Angola", "Angola"], code: "AO" },
  { name: ["Anguilla", "Anguilla", "Anguilla", "Anguilla"], code: "AI" },
  { name: ["Antarctica", "Antarctique", "Antarktis", "Antartide"], code: "AQ" },
  { name: ["Antigua and Barbuda", "Antigua-et-Barbuda", "Antigua und Barbuda", "Antigua e Barbuda"], code: "AG" },
  { name: ["Argentina", "Argentine", "Argentinien", "Argentina"], code: "AR" },
  { name: ["Armenia", "Arménie", "Armenien", "Armenia"], code: "AM" },
  { name: ["Aruba", "Aruba", "Aruba", "Aruba"], code: "AW" },
  { name: ["Australia", "Australie", "Australien", "Australia"], code: "AU" },
  { name: ["Austria", "L'Autriche", "Österreich", "Austria"], code: "AT" },
  { name: ["Azerbaijan", "Azerbaïdjan", "Aserbaidschan", "Azerbaijan"], code: "AZ" },
  { name: ["Bahamas", "Bahamas", "Bahamas", "Bahamas"], code: "BS" },
  { name: ["Bahrain", "Bahrein", "Bahrain", "Bahrain"], code: "BH" },
  { name: ["Bangladesh", "Bangladesh", "Bangladesch", "Bangladesh"], code: "BD" },
  { name: ["Barbados", "Barbade", "Barbados", "Barbados"], code: "BB" },
  { name: ["Belarus", "Biélorussie", "Weißrussland", "Bielorussia"], code: "BY" },
  { name: ["Belgium", "Belgique", "Belgien", "Belgio"], code: "BE" },
  { name: ["Belize", "Belize", "Belize", "Belize"], code: "BZ" },
  { name: ["Benin", "Bénin", "Benin", "Benin"], code: "BJ" },
  { name: ["Bermuda", "Bermudes", "Bermuda", "Bermuda"], code: "BM" },
  { name: ["Bhutan", "Bhoutan", "Bhutan", "Bhutan"], code: "BT" },
  { name: ["Bolivia", "Bolivie", "Bolivien", "Bolivia"], code: "BO" },
  { name: ["Bosnia and Herzegovina", "Bosnie Herzégovine", "Bosnien und Herzegowina", "Bosnia Erzegovina"], code: "BA" },
  { name: ["Botswana", "Botswana", "Botswana", "Botswana"], code: "BW" },
  { name: ["Bouvet Island", "Bouvet Island", "Bouvetinsel", "Isola Bouvet"], code: "BV" },
  { name: ["Brazil", "Brésil", "Brasilien", "Brasile"], code: "BR" },
  {
    name: [
      "British Indian Ocean Territory",
      "Territoire britannique de l'océan Indien",
      "Britisches Territorium des Indischen Ozeans",
      "Territorio britannico dell'Oceano Indiano"
    ],
    code: "IO"
  },
  { name: ["Brunei Darussalam", "Brunei Darussalam", "Brunei Darussalam", "Brunei Darussalam"], code: "BN" },
  { name: ["Bulgaria", "Bulgarie", "Bulgarien", "Bulgaria"], code: "BG" },
  { name: ["Burkina Faso", "Burkina Faso", "Burkina Faso", "Burkina Faso"], code: "BF" },
  { name: ["Burundi", "Burundi", "Burundi", "Burundi"], code: "BI" },
  { name: ["Cambodia", "Cambodge", "Kambodscha", "Cambogia"], code: "KH" },
  { name: ["Cameroon", "Cameroun", "Kamerun", "Camerun"], code: "CM" },
  { name: ["Canada", "Canada", "Kanada", "Canada"], code: "CA" },
  { name: ["Cape Verde", "Cap-Vert", "Kap Verde", "capo Verde"], code: "CV" },
  { name: ["Cayman Islands", "Îles Caïmans", "Cayman Inseln", "Isole Cayman"], code: "KY" },
  {
    name: ["Central African Republic", "République centrafricaine", "Zentralafrikanische Republik", "Repubblica Centrafricana"],
    code: "CF"
  },
  { name: ["Chad", "Tchad", "Tschad", "Chad"], code: "TD" },
  { name: ["Chile", "Chili", "Chile", "Chile"], code: "CL" },
  { name: ["China", "Chine", "China", "Cina"], code: "CN" },
  { name: ["Christmas Island", "L'île de noël", "Weihnachtsinsel", "Isola di Natale"], code: "CX" },
  { name: ["Cocos (Keeling) Islands", "Îles Cocos (Keeling)", "Kokosinseln (Keelinginseln)", "Isole Cocos (Keeling)"], code: "CC" },
  { name: ["Colombia", "Colombie", "Kolumbien", "Colombia"], code: "CO" },
  { name: ["Comoros", "Les Comores", "Komoren", "Comoros"], code: "KM" },
  { name: ["Congo", "Congo", "Kongo", "Congo"], code: "CG" },
  {
    name: [
      "Congo, The Democratic Republic of the",
      "Congo, République démocratique du",
      "Kongo, Demokratische Republik",
      "Congo, Repubblica Democratica del"
    ],
    code: "CD"
  },
  { name: ["Cook Islands", "les Îles Cook", "Cookinseln", "Isole Cook"], code: "CK" },
  { name: ["Costa Rica", "Costa Rica", "Costa Rica", "Costa Rica"], code: "CR" },
  { name: ["Cote D'Ivoire", "Côte d'Ivoire", "Elfenbeinküste", "Costa d'Avorio"], code: "CI" },
  { name: ["Croatia", "Croatie", "Kroatien", "Croazia"], code: "HR" },
  { name: ["Cuba", "Cuba", "Kuba", "Cuba"], code: "CU" },
  { name: ["Cyprus", "Chypre", "Zypern", "Cipro"], code: "CY" },
  { name: ["Czech Republic", "République Tchèque", "Tschechische Republik", "Repubblica Ceca"], code: "CZ" },
  { name: ["Denmark", "Danemark", "Dänemark", "Danimarca"], code: "DK" },
  { name: ["Djibouti", "Djibouti", "Dschibuti", "Gibuti"], code: "DJ" },
  { name: ["Dominica", "La Dominique", "Dominica", "Dominica"], code: "DM" },
  { name: ["Dominican Republic", "République Dominicaine", "Dominikanische Republik", "Repubblica Dominicana"], code: "DO" },
  { name: ["Ecuador", "Équateur", "Ecuador", "Ecuador"], code: "EC" },
  { name: ["Egypt", "Egypte", "Ägypten", "Egitto"], code: "EG" },
  { name: ["El Salvador", "Le Salvador", "El Salvador", "El Salvador"], code: "SV" },
  { name: ["Equatorial Guinea", "Guinée Équatoriale", "Äquatorialguinea", "Guinea Equatoriale"], code: "GQ" },
  { name: ["Eritrea", "Erythrée", "Eritrea", "l'Eritrea"], code: "ER" },
  { name: ["Estonia", "Estonie", "Estland", "Estonia"], code: "EE" },
  { name: ["Ethiopia", "Ethiopie", "Äthiopien", "Etiopia"], code: "ET" },
  {
    name: ["Falkland Islands (Malvinas)", "Îles Falkland (Malvinas)", "Falklandinseln (Malvinas)", "Isole Falkland (Malvinas)"],
    code: "FK"
  },
  { name: ["Faroe Islands", "Îles Féroé", "Färöer Inseln", "Isole Faroe"], code: "FO" },
  { name: ["Fiji", "Fidji", "Fidschi", "Fiji"], code: "FJ" },
  { name: ["Finland", "Finlande", "Finnland", "Finlandia"], code: "FI" },
  { name: ["France", "France", "Frankreich", "Francia"], code: "FR" },
  { name: ["French Guiana", "Guinée Française", "Französisch-Guayana", "Guiana francese"], code: "GF" },
  { name: ["French Polynesia", "Polynésie française", "Französisch Polynesien", "Polinesia francese"], code: "PF" },
  {
    name: ["French Southern Territories", "Terres Australes Françaises", "Südfranzösische Territorien", "Territori della Francia del sud"],
    code: "TF"
  },
  { name: ["Gabon", "Gabon", "Gabun", "Gabon"], code: "GA" },
  { name: ["Gambia", "Gambie", "Gambia", "Gambia"], code: "GM" },
  { name: ["Georgia", "Géorgie", "Georgia", "Georgia"], code: "GE" },
  { name: ["Germany", "Allemagne", "Deutschland", "Germania"], code: "DE" },
  { name: ["Ghana", "Ghana", "Ghana", "Ghana"], code: "GH" },
  { name: ["Gibraltar", "Gibraltar", "Gibraltar", "Gibilterra"], code: "GI" },
  { name: ["Greece", "Grèce", "Griechenland", "Grecia"], code: "GR" },
  { name: ["Greenland", "Groenland", "Griechenland", "Groenlandia"], code: "GL" },
  { name: ["Grenada", "Grenade", "Grönland", "Grenada"], code: "GD" },
  { name: ["Guadeloupe", "Guadeloupe", "Guadeloupe", "Guadeloupe"], code: "GP" },
  { name: ["Guam", "Guam", "Guam", "Guam"], code: "GU" },
  { name: ["Guatemala", "Guatemala", "Guatemala", "Guatemala"], code: "GT" },
  { name: ["Guernsey", "Guernesey", "Guernsey", "Maglione"], code: "GG" },
  { name: ["Guinea", "Guinée", "Guinea", "Guinea"], code: "GN" },
  { name: ["Guinea-Bissau", "Guinée Bissau", "Guinea-Bissau", "Guinea-Bissau"], code: "GW" },
  { name: ["Guyana", "Guyane", "Guyana", "Guyana"], code: "GY" },
  { name: ["Haiti", "Haïti", "Haiti", "Haiti"], code: "HT" },
  {
    name: [
      "Heard Island and Mcdonald Islands",
      "Heard Island et les îles Mcdonald",
      "Heard Island und Mcdonald Islands",
      "Heard Island e Mcdonald Islands"
    ],
    code: "HM"
  },
  {
    name: [
      "Holy See (Vatican City State)",
      "Saint-Siège (État de la cité du Vatican)",
      "Heiliger Stuhl",
      "Santa Sede (Stato della Città del Vaticano)"
    ],
    code: "VA"
  },
  { name: ["Honduras", "Honduras", "Honduras", "Honduras"], code: "HN" },
  { name: ["Hong Kong", "Hong Kong", "Hongkong", "Hong Kong"], code: "HK" },
  { name: ["Hungary", "Hongrie", "Ungarn", "Ungheria"], code: "HU" },
  { name: ["Iceland", "Islande", "Island", "Islanda"], code: "IS" },
  { name: ["India", "Inde", "Indien", "India"], code: "IN" },
  { name: ["Indonesia", "Indonésie", "Indonesien", "Indonesia"], code: "ID" },
  {
    name: ["Iran, Islamic Republic Of", "Iran (République islamique d", "Iran, Islamische Republik", "Iran (Repubblica Islamica del"],
    code: "IR"
  },
  { name: ["Iraq", "Irak", "Irak", "Iraq"], code: "IQ" },
  { name: ["Ireland", "Irlande", "Irland", "Irlanda"], code: "IE" },
  { name: ["Isle of Man", "Île de man", "Isle of Man", "Isola di Man"], code: "IM" },
  { name: ["Israel", "Israël", "Israel", "Israele"], code: "IL" },
  { name: ["Italy", "Italie", "Italien", "Italia"], code: "IT" },
  { name: ["Jamaica", "Jamaïque", "Jamaika", "Giamaica"], code: "JM" },
  { name: ["Japan", "Japon", "Japan", "Giappone"], code: "JP" },
  { name: ["Jersey", "Jersey", "Jersey", "Maglia"], code: "JE" },
  { name: ["Jordan", "Jordan", "Jordan", "Giordania"], code: "JO" },
  { name: ["Kazakhstan", "Kazakhstan", "Kasachstan", "Kazakistan"], code: "KZ" },
  { name: ["Kenya", "Kenya", "Kenia", "Kenia"], code: "KE" },
  { name: ["Kiribati", "Kiribati", "Kiribati", "Kiribati"], code: "KI" },
  {
    name: [
      "Korea, Democratic People'S Republic of",
      "République populaire démocratique de Corée",
      "Korea, Demokratische Volksrepublik",
      "Corea, Repubblica Democratica Popolare di"
    ],
    code: "KP"
  },
  { name: ["Korea, Republic of", "Corée, République de", "Korea, Republik von", "Corea, Repubblica di"], code: "KR" },
  { name: ["Kuwait", "Koweit", "Kuwait", "Kuwait"], code: "KW" },
  { name: ["Kyrgyzstan", "Kirghizistan", "Kirgisistan", "Kyrgyzstan"], code: "KG" },
  {
    name: [
      "Lao People'S Democratic Republic",
      "République démocratique populaire lao",
      "Demokratische Volksrepublik Laos",
      "Repubblica Democratica Popolare del Laos"
    ],
    code: "LA"
  },
  { name: ["Latvia", "Lettonie", "Lettland", "Lettonia"], code: "LV" },
  { name: ["Lebanon", "Liban", "Libanon", "Libano"], code: "LB" },
  { name: ["Lesotho", "Lesotho", "Lesotho", "Lesoto"], code: "LS" },
  { name: ["Liberia", "Libéria", "Liberia", "Liberia"], code: "LR" },
  { name: ["Libyan Arab Jamahiriya", "Jamahiriya Arabe Libyenne", "Libyscher Araber Jamahiriya", "Jamahiriya araba libica"], code: "LY" },
  { name: ["Liechtenstein", "Liechtenstein", "Liechtenstein", "Liechtenstein"], code: "LI" },
  { name: ["Lithuania", "Lituanie", "Litauen", "Lituania"], code: "LT" },
  { name: ["Luxembourg", "Luxembourg", "Luxemburg", "Lussemburgo"], code: "LU" },
  { name: ["Macao", "Macao", "Macao", "Macao"], code: "MO" },
  {
    name: [
      "Macedonia, The Former Yugoslav Republic of",
      "Macédoine, l'ex-République yougoslave de",
      "Mazedonien, die ehemalige jugoslawische Republik",
      "Macedonia, ex Repubblica iugoslava di"
    ],
    code: "MK"
  },
  { name: ["Madagascar", "Madagascar", "Madagaskar", "Madagascar"], code: "MG" },
  { name: ["Malawi", "Malawi", "Malawi", "Malawi"], code: "MW" },
  { name: ["Malaysia", "Malaisie", "Malaysia", "Malaysia"], code: "MY" },
  { name: ["Maldives", "Maldives", "Malediven", "Maldive"], code: "MV" },
  { name: ["Mali", "Mali", "Mali", "Mali"], code: "ML" },
  { name: ["Malta", "Malte", "Malta", "Malta"], code: "MT" },
  { name: ["Marshall Islands", "Iles Marshall", "Marshallinseln", "Isole Marshall"], code: "MH" },
  { name: ["Martinique", "Martinique", "Martinique", "Martinique"], code: "MQ" },
  { name: ["Mauritania", "Mauritanie", "Mauretanien", "Mauritania"], code: "MR" },
  { name: ["Mauritius", "Maurice", "Mauritius", "Mauritius"], code: "MU" },
  { name: ["Mayotte", "Mayotte", "Mayotte", "Mayotte"], code: "YT" },
  { name: ["Mexico", "Mexique", "Mexiko", "Messico"], code: "MX" },
  {
    name: ["Micronesia, Federated States of", "Micronésie, États fédérés de", "Mikronesien, Föderierte Staaten von", "Micronesia, Stati Federati di"],
    code: "FM"
  },
  { name: ["Moldova, Republic of", "Moldova, République de", "Moldawien, Republik", "Moldavia, Repubblica di"], code: "MD" },
  { name: ["Monaco", "Monaco", "Monaco", "Monaco"], code: "MC" },
  { name: ["Mongolia", "Mongolie", "Mongolei", "Mongolia"], code: "MN" },
  { name: ["Montserrat", "Montserrat", "Montserrat", "Montserrat"], code: "MS" },
  { name: ["Morocco", "Maroc", "Marokko", "Marocco"], code: "MA" },
  { name: ["Mozambique", "Mozambique", "Mosambik", "Mozambico"], code: "MZ" },
  { name: ["Myanmar", "Myanmar", "Myanmar", "Myanmar"], code: "MM" },
  { name: ["Namibia", "Namibie", "Namibia", "Namibia"], code: "NA" },
  { name: ["Nauru", "Nauru", "Nauru", "Nauru"], code: "NR" },
  { name: ["Nepal", "Népal", "Nepal", "Nepal"], code: "NP" },
  { name: ["Netherlands", "Pays-Bas", "Niederlande", "Olanda"], code: "NL" },
  { name: ["Netherlands Antilles", "Antilles néerlandaises", "Niederländische Antillen", "Antille Olandesi"], code: "AN" },
  { name: ["New Caledonia", "Nouvelle Calédonie", "Neu-Kaledonien", "Nuova Caledonia"], code: "NC" },
  { name: ["New Zealand", "Nouvelle-Zélande", "Neuseeland", "Nuova Zelanda"], code: "NZ" },
  { name: ["Nicaragua", "Nicaragua", "Nicaragua", "Nicaragua"], code: "NI" },
  { name: ["Niger", "Niger", "Niger", "Niger"], code: "NE" },
  { name: ["Nigeria", "Nigeria", "Nigeria", "Nigeria"], code: "NG" },
  { name: ["Niue", "Niue", "Niue", "Niue"], code: "NU" },
  { name: ["Norfolk Island", "l'ile de Norfolk", "Norfolkinsel", "Isole Norfolk"], code: "NF" },
  { name: ["Northern Mariana Islands", "Îles Mariannes du Nord", "Nördliche Marianneninseln", "Isole Marianne settentrionali"], code: "MP" },
  { name: ["Norway", "Norvège", "Norwegen", "Norvegia"], code: "NO" },
  { name: ["Oman", "Oman", "Oman", "Oman"], code: "OM" },
  { name: ["Pakistan", "Pakistan", "Pakistan", "Pakistan"], code: "PK" },
  { name: ["Palau", "Palau", "Palau", "Palau"], code: "PW" },
  {
    name: ["Palestinian Territory, Occupied", "Territoire palestinien occupé", "Palästinensisches Gebiet", "Territorio palestinese"],
    code: "PS"
  },
  { name: ["Panama", "Panama", "Panama", "Panama"], code: "PA" },
  { name: ["Papua New Guinea", "Papouasie Nouvelle Guinée", "Papua Neu-Guinea", "Papua Nuova Guinea"], code: "PG" },
  { name: ["Paraguay", "Le Paraguay", "Paraguay", "Paraguay"], code: "PY" },
  { name: ["Peru", "Pérou", "Peru", "Perù"], code: "PE" },
  { name: ["Philippines", "Philippines", "Philippinen", "Filippine"], code: "PH" },
  { name: ["Pitcairn", "Pitcairn", "Pitcairn", "Pitcairn"], code: "PN" },
  { name: ["Poland", "Pologne", "Polen", "Polonia"], code: "PL" },
  { name: ["Portugal", "le Portugal", "Portugal", "Portogallo"], code: "PT" },
  { name: ["Puerto Rico", "Porto Rico", "Puerto Rico", "Puerto Rico"], code: "PR" },
  { name: ["Qatar", "Qatar", "Katar", "Qatar"], code: "QA" },
  { name: ["Reunion", "Réunion", "Wiedervereinigung", "Riunione"], code: "RE" },
  { name: ["Romania", "Roumanie", "Rumänien", "Romania"], code: "RO" },
  { name: ["Russian Federation", "Fédération Russe", "Russische Föderation", "Federazione Russa"], code: "RU" },
  { name: ["RWANDA", "RWANDA", "RWANDA", "RUANDA"], code: "RW" },
  { name: ["Saint Helena", "Sainte Hélène", "St. Helena", "Sant'Elena"], code: "SH" },
  { name: ["Saint Kitts and Nevis", "Saint-Christophe-et-Niévès", "St. Kitts und Nevis", "Saint Kitts e Nevis"], code: "KN" },
  { name: ["Saint Lucia", "Sainte-Lucie", "St. Lucia", "Santa Lucia"], code: "LC" },
  {
    name: ["Saint Pierre and Miquelon", "Saint Pierre et Miquelon", "Saint Pierre und Miquelon", "Saint Pierre e Miquelon"],
    code: "PM"
  },
  {
    name: [
      "Saint Vincent and the Grenadines",
      "Saint-Vincent-et-les-Grenadines",
      "St. Vincent und die Grenadinen",
      "Saint Vincent e Grenadine"
    ],
    code: "VC"
  },
  { name: ["Samoa", "Samoa", "Samoa", "Samoa"], code: "WS" },
  { name: ["San Marino", "Saint Marin", "San Marino", "San Marino"], code: "SM" },
  { name: ["Sao Tome and Principe", "Sao Tomé et Principe", "Sao Tome und Principe", "Sao Tome e Principe"], code: "ST" },
  { name: ["Saudi Arabia", "Arabie Saoudite", "Saudi Arabien", "Arabia Saudita"], code: "SA" },
  { name: ["Senegal", "Sénégal", "Senegal", "Senegal"], code: "SN" },
  { name: ["Serbia and Montenegro", "Serbie et Monténégro", "Serbien und Montenegro", "Serbia e Montenegro"], code: "CS" },
  { name: ["Seychelles", "les Seychelles", "Seychellen", "Seychelles"], code: "SC" },
  { name: ["Sierra Leone", "Sierra Leone", "Sierra Leone", "Sierra Leone"], code: "SL" },
  { name: ["Singapore", "Singapour", "Singapur", "Singapore"], code: "SG" },
  { name: ["Slovakia", "Slovaquie", "Slowakei", "Slovacchia"], code: "SK" },
  { name: ["Slovenia", "La Slovénie", "Slowenien", "Slovenia"], code: "SI" },
  { name: ["Solomon Islands", "îles Salomon", "Salomon-Inseln", "Isole Salomone"], code: "SB" },
  { name: ["Somalia", "Somalie", "Somalia", "Somalia"], code: "SO" },
  { name: ["South Africa", "Afrique du Sud", "Südafrika", "Sud Africa"], code: "ZA" },
  {
    name: [
      "South Georgia and the South Sandwich Islands",
      "Géorgie du Sud et les îles Sandwich du Sud",
      "Süd-Georgien und die südlichen Sandwich-Inseln",
      "Georgia del Sud e Isole Sandwich Meridionali"
    ],
    code: "GS"
  },
  { name: ["Spain", "Espagne", "Spanien", "Spagna"], code: "ES" },
  { name: ["Sri Lanka", "Sri Lanka", "Sri Lanka", "Sri Lanka"], code: "LK" },
  { name: ["Sudan", "Soudan", "Sudan", "Sudan"], code: "SD" },
  { name: ["Suriname", "Suriname", "Suriname", "Suriname"], code: "SR" },
  { name: ["Svalbard and Jan Mayen", "Svalbard et Jan Mayen", "Spitzbergen und Jan Mayen", "Svalbard e Jan Mayen"], code: "SJ" },
  { name: ["Swaziland", "Swaziland", "Swasiland", "Swaziland"], code: "SZ" },
  { name: ["Sweden", "Suède", "Schweden", "Svezia"], code: "SE" },

  { name: ["Syrian Arab Republic", "République arabe syrienne", "Syrische Arabische Republik", "Repubblica Araba Siriana"], code: "SY" },
  {
    name: ["Taiwan, Province of China", "Taiwan, Province de Chine", "Taiwan, Provinz Chinas", "Taiwan, provincia cinese"],
    code: "TW"
  },
  { name: ["Tajikistan", "Tadjikistan", "Tadschikistan", "Tajikistan"], code: "TJ" },
  {
    name: ["Tanzania, United Republic of", "Tanzanie, République Unie de", "Tansania, Vereinigte Republik", "Tanzania, Repubblica unita di"],
    code: "TZ"
  },
  { name: ["Thailand", "Thaïlande", "Thailand", "Tailandia"], code: "TH" },
  { name: ["Timor-Leste", "Timor-Leste", "Timor-Leste", "Timor Est"], code: "TL" },
  { name: ["Togo", "Aller", "Gehen", "Andare"], code: "TG" },
  { name: ["Tokelau", "Tokélaou", "Tokelau", "Tokelau"], code: "TK" },
  { name: ["Tonga", "Tonga", "Tonga", "Tonga"], code: "TO" },
  { name: ["Trinidad and Tobago", "Trinité-et-Tobago", "Trinidad und Tobago", "Trinidad e Tobago"], code: "TT" },
  { name: ["Tunisia", "Tunisie", "Tunesien", "Tunisia"], code: "TN" },
  { name: ["Turkey", "Turquie", "Truthahn", "Tacchino"], code: "TR" },
  { name: ["Turkmenistan", "Turkménistan", "Turkmenistan", "Turkmenistan"], code: "TM" },
  { name: ["Turks and Caicos Islands", "îles Turques-et-Caïques", "Turks- und Caicosinseln", "Isole Turks e Caicos"], code: "TC" },
  { name: ["Tuvalu", "Tuvalu", "Tuvalu", "Tuvalu"], code: "TV" },
  { name: ["Uganda", "Ouganda", "Uganda", "Uganda"], code: "UG" },
  { name: ["Ukraine", "Ukraine", "Ukraine", "Ucraina"], code: "UA" },
  { name: ["United Arab Emirates", "Emirats Arabes Unis", "Vereinigte Arabische Emirate", "Emirati Arabi Uniti"], code: "AE" },
  { name: ["United Kingdom", "Royaume-Uni", "Großbritannien", "Regno Unito"], code: "GB" },
  { name: ["United States", "États Unis", "Vereinigte Staaten", "stati Uniti"], code: "US" },
  {
    name: [
      "United States Minor Outlying Islands",
      "Îles mineures éloignées des États-Unis",
      "USA, kleinere ausgelagerte Inseln",
      "Isole minori esterne degli Stati Uniti"
    ],
    code: "UM"
  },
  { name: ["Uruguay", "Uruguay", "Uruguay", "Uruguay"], code: "UY" },
  { name: ["Uzbekistan", "Ouzbekistan", "Usbekistan", "Uzbekistan"], code: "UZ" },
  { name: ["Vanuatu", "Vanuatu", "Vanuatu", "Vanuatu"], code: "VU" },
  { name: ["Venezuela", "Venezuela", "Venezuela", "Venezuela"], code: "VE" },
  { name: ["Viet Nam", "Viet Nam", "Vietnam", "Vietnam"], code: "VN" },
  {
    name: ["Virgin Islands, British", "Îles vierges britanniques", "Virgin Inseln, Britisch", "Isole Vergini Britanniche"],
    code: "VG"
  },
  { name: ["Virgin Islands, U.S.", "Îles Vierges américaines", "Amerikanische Jungferninseln", "Isole Vergini Americane"], code: "VI" },
  { name: ["Wallis and Futuna", "Wallis et Futuna", "Wallis und Futuna", "Wallis e Futuna"], code: "WF" },
  { name: ["Western Sahara", "Sahara occidental", "Westsahara", "Sahara occidentale"], code: "EH" },
  { name: ["Yemen", "Yémen", "Jemen", "Yemen"], code: "YE" },
  { name: ["Zambia", "Zambie", "Sambia", "Zambia"], code: "ZM" },
  { name: ["Zimbabwe", "Zimbabwe", "Zimbabwe", "Zimbabwe"], code: "ZW" }
];

export const months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export const years = [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];

export const categoryList = [
  [
    "Apartment", "House, chalet, rustico", "Furnished dwelling", "Parging space, garage", "Office", "Commercial & industry", "Storage room"
  ],
  [
    "Appartement", "Maison, chalet, villa", "Logement meublé", "Place de parc, garage", "Bureau", "Commerce et industrie", "Pièce de stockage"
  ],
  [
    "Wohnung", "Haus", "Möbliertes Wohnobjekt", "Parkplatz Garage", "Büro", "Gewerbe", "Lager"
  ],
  [
    "Appartamento", "Casa, chalet, rustico", "Abitazione ammobiliata", "Parcheggio space, garage", "Ufficio", "Commercio e industria", "Magazzino"
  ]
];

export const propertyList = [
  // ["Apartment", "Roof flat", "Terrace flat", "Mansard", "Bifamiliar house", "Farm house", "Chalet", "Cellar compartment", "Duplex", "Studio", "Bachelor flat", "Single house", "Terrace house", "Cave house / earthen house", "Rustic house", "Attic compartment", "Attic flat", "Single room", "Loft", "Row house", "Villa", "Castle", "Granny flat", "Hobby room", "Allottment garden"],
  [
    ["Apartment", "Roof flat", "Terrace flat", "Mansard", "Duplex", "Studio", "Bachelor flat", "Attic flat", "Single room", "Loft"],
    ["Single house", "Terrace house", "Cave house / earthen house", "Row house", "Villa", "Castle", "Chalet", "Bifamiliar house", "Farm house", "Granny flat", "Rustic house"],
    [],
    ["Open slot", "Double garage", "Boat landing stage", "Horse box", "Covered slot", "Underground garage", "Bike covered parking", "Boat mooring", "Single garage", "Boat dry dock", "Bike outdoor parking"],
    [],
    ["Agricultural installation", "Mountain farm", "Farm", "Hotel", "Restaurant", "Coffeehouse", "Bar", "Club / Disco", "Casino", "Movie / Theater", "Squash / Badminton", "Indoor tennis court", "Tennis court", "Sports hall", "Campground", "Outdoor swimming pool", "Indoor swimming pool", "Golf course", "Motel", "Pub", "Shop", "Advertising area", "Commercial", "Practice", "Kiosk", "Gardening", "Fuel station", "Garage", "Cheese factory", "Butchery", "Bakery", "Hairdresser", "Shopping centre", "Factory", "Industrial object", "Arcade", "Atelier", "Living / Commercial building", "Library", "Laboratory", "Mini-golf course", "Nursing home", "Sanatorium", "Workshop", "Party room", "Sauna", "Sunroom", "Carpentry shop", "Old-age home", "Department store", "Home", "Display window", "Parking garage", "Parking surface"],
    []
  ],
  [
    ["Appartement", "App. dernier étage", "App. en terrasse", "Mansarde", "Duplex", "Studio", "App. intégré", "Attique", "Chambre", "Loft"],
    ["Maison individuelle", "Maison en terrasse", "Habitation dans la terre", "Maison contiguë", "Villa", "Château", "Chalet", "Maison jumelée", "Ferme", "Dépendance", "Rustico"],
    [],
    ["Place ouverte", "Garage double", "Place ext. à bâteaux", "Box d'écurie", "Place couverte", "Place souterraine", "Halle à motos", "Place à bâteau balisée", "Garage individuel", "Halle à bâteaux", "Place ext. à motos"],
    [],
    ["Exploitation agricole", "Exploitation montagne", "Ferme", "Hôtel", "Restaurant", "Café", "Bar", "Club / Disco", "Casino", "Cinéma / Théâtre", "Squash / Badminton", "Halle de tennis", "Place de tennis", "Installation sportive", "Camping", "Piscine ouverte", "Piscine couverte", "Terrain de golf", "Motel", "Pub", "Commerce", "Exposition", "Industrie", "Cabinet médical", "Kiosque", "Jardinerie", "Station service", "Garage", "Fromagerie", "Boucherie", "Boulangerie", "Salon de coiffure", "Centre commercial", "Fabrique", "Objet industriel", "Arcade", "Atelier", "Imm. com. & hab.", "Bibliothèque", "Laboratoire", "Place de minigolf", "Maison de soins", "Halle d'équitation", "Sanatorium", "Atelier artisanal", "Salle des fêtes", "Sauna", "Solarium", "Menuiserie", "Maison de retraite", "Immeuble commercial", "Home", "Vitrine", "Parking à étages", "Surface de parking"],
    []
  ],
  [
    ["Wohnung", "Dachwohnung", "Terrassenwohnung", "Mansarde", "Maisonette / Duplex", "Studio", "Einliegerwohnung", "Attikawohnung", "Einzelzimmer", "Loft"],
    ["Einfamilienhaus", "Terrassenhaus", "Höhlen- / Erdhaus", "Reihenfamilienhaus", "Villa", "Schloss", "Chalet", "Doppeleinfamilienhaus", "Bauernhaus", "Stöckli", "Rustico"],
    [],
    ["Offener Parkplatz", "Doppelgarage", "Boot Stegplatz", "Stallboxe", "Unterstand", "Tiefgarage", "Moto Hallenplatz", "Boot Bojenplatz", "Einzelgarage", "Boot Hallenplatz", "Moto Aussenplatz"],
    [],
    ["Landwirtschaftsbetrieb", "Alpwirtschaft", "Farm", "Hotel", "Restaurant", "Café", "Bar", "Club / Disco", "Casino", "Kino / Theater", "Squash / Badminton", "Tennishalle", "Tennisplatz", "Sportanlage", "Camping- / Zeltplatz", "Freibad", "Hallenbad", "Golfplatz", "Motel", "Pub", "Ladenfläche", "Werbefläche", "Gewerbe", "Praxis", "Kiosk", "Gärtnerei", "Tankstelle", "Autogarage", "Käserei", "Metzgerei", "Bäckerei", "Coiffeursalon", "Shoppingcenter", "Fabrik", "Industrieobjekt", "Arcade", "Atelier", "Wohn- / Geschäftshaus", "Bücherei", "Labor", "Minigolfplatz", "Pflegeheim", "Reithalle", "Sanatorium", "Werkstatt", "Partyraum", "Sauna", "Solarium", "Schreinerei", "Altersheim", "Geschäftshaus", "Heim", "Schaufenster", "Parkhaus", "Parkfläche"],
    []
  ],
  [
    ["Appartamento", "App. ultimo piano", "App. a terrazza", "Mansarda", "Duplex", "Studio", "App. attiguo", "Attico", "Camera", "Loft"],
    ["Casa unifamiliare", "Casa a terrazza", "Casa interrata", "Casa a schiera", "Villa", "Castello", "Chalet", "Casa bifamiliare", "Fattoria", "Stöckli", "Rustico"],
    [],
    ["Parcheggio aperto", "Garage doppio", "Attracco barca esteriore", "Box in stalla", "Parcheggio coperto", "Parcheggio sotterraneo", "Posteggio moto in garage", "Attracco barca (boa)", "Garage singolo", "Posteggio barca interno", "Posteggio moto esterno"],
    [],
    ["Sfruttamento agricolo", "Sfruttamento montagna", "Fattoria", "Hotel", "Ristorante", "Caffè", "Bar", "Club / Disco", "Casinò", "Cinema / Teatro", "Squash / Badminton", "Campo da tennis interno", "Campo da tennis esterno", "Impianto sportivo", "Campeggio", "Piscina esterna", "Piscina coperta", "Campo da golf", "Motel", "Pub", "Commercio", "Esposizioni", "Industrie", "Studio medico", "Chiosco", "Azienda floricoltura", "Stazione di benzina", "Autorimessa", "Caseificio", "Macelleria", "Panetteria", "Salone da parrucchiere", "Centro commerciale", "Fabbrica", "Oggetti industriali", "Arcade", "Atelier", "Immob. com. e abitativo", "Biblioteca", "Laboratorio", "Campo da minigolf", "Casa di cura", "Maneggio", "Sanatorio", "Officina", "Locale per feste", "Sauna", "Solarium", "Falegnameria", "Casa di riposo", "Edificio commerciale", "Istituto", "Vetrina", "Autosilo", "Posteggio"],
    []
  ]

];

export const proximiteList = [
  [ 
    "DownTown",
    "Village",
    "Villas area",
    "verdant",
    "Silent/quiet",
    "mountains",
    "Lac",
    "Port",
    "Marina",
    "Vineyard",
    "Shops",
    "Shopping street",
    "Bank",
    "Post",
    "Restaurant(s)",
    "Station",
    "Bus stop",
    "Tram stop",
    "Highway entrance/exit",
    "Children welcome",
    "Playground",
    "Creche/nursery",
    "Preschool",
    "Primary school",
    "Secondary school",
    "Middle School",
    "University",
    "Sports Center",
    "Near agolf course",
    "Museum",
    "Cinema",
    "Ski slope",
    "Ski station",
    "Lifts",
    "Cross-country",
    "Hiking trails",
    "Bike path",
    "Near customs",
    "Religious monuments"
  ],
  [ 
     "Centre ville",
     "Village",
     "Zone de villas",
     "verdoyant",
     "Silencieux / silencieux",
     "les montagnes",
     "Lac",
     "Port",
     "Marina",
     "Vignoble",
     "Magasins",
     "Rue commerçante",
     "Banque",
     "Poster",
     "Restaurant(s)",
     "Gare",
     "Arrêt de bus",
     "Arrêt de tramway",
     "Entrée / sortie d'autoroute",
     "Les enfants sont les bienvenus",
     "Cour de récréation",
     "Crèche / Garderie",
     "Préscolaire",
     "École primaire",
     "École secondaire",
     "École intermédiaire",
     "Université",
     "Centre sportif",
     "Proche du golf",
     "Musée",
     "Cinéma",
     "Pente de ski",
     "Station de ski",
     "Ascenseurs",
     "Cross-country",
     "Sentiers de randonnée",
     "Piste cyclable",
     "Près des douanes",
     "Monuments religieux"
  ],
  [ 
    "Innenstadt",
     "Dorf",
     "Villas Bereich",
     "grün",
     "Still / leise",
     "Berge",
     "Lac",
     "Hafen",
     "Yachthafen",
     "Weinberg",
     "Geschäfte",
     "Einkaufsstraße",
     "Bank",
     "Post",
     "Restaurant (s)",
     "Bahnhof",
     "Bushaltestelle",
     "Straßenbahnhaltestelle",
     "Autobahn Einfahrt / Ausfahrt",
     "Kinder willkommen",
     "Spielplatz",
     "Kinderkrippe / Kindergarten",
     "Vorschule",
     "Grundschule",
     "Weiterführende Schule",
     "Mittelschule",
     "Universität",
     "Sportzentrum",
     "In der Nähe eines Golfplatzes",
     "Museum",
     "Kino",
     "Skipiste",
     "Skistation",
     "Aufzüge",
     "Querfeldein",
     "Wanderpfade",
     "Fahrradweg",
     "In der Nähe des Zolls",
     "Religiöse Denkmäler"
  ],
  [ 
    "Centro",
     "Villaggio",
     "Area ville",
     "verdeggiante",
     "Silent / quiet",
     "montagne",
     "Lac",
     "Porta",
     "Marina",
     "Vigneto",
     "Negozi",
     "Via dello shopping",
     "Banca",
     "Inviare",
     "Ristorante (s)",
     "Stazione",
     "Fermata dell'autobus",
     "Fermata del tram",
     "Ingresso / uscita autostrada",
     "Bambini benvenuti",
     "Terreno di gioco",
     "Creche / scuola materna",
     "Prescolare",
     "Scuola elementare",
     "Scuola media",
     "Scuole medie",
     "Università",
     "Centro sportivo",
     "Vicino al corso di agolf",
     "Museo",
     "Cinema",
     "Pista da sci",
     "Stazione sciistica",
     "Ascensori",
     "Sci di fondo",
     "Sentieri",
     "Pista ciclabile",
     "Vicino alla dogana",
     "Monumenti religiosi"
  ]
];

export const facilityList = [
  [
    "View",
    "Parking",
    "Balcony",
    "Garage",
    "Utility Room",
    "Cave",
    "Galetas",
    "Terrace",
    "Veranda",
    "Fireplace",
    "Atelier",
    "Elevator",
    "Storage space",
    "Cable TV",
    "ISDN connection",
    "Suitable for children",
    "Wheelchair accessible",
    "Pets allowed",
    "Construction Minergie",
    "Minergie certified",
    "Swimming pool"
  ],
  [
  "Vue",
   "Parking",
   "Balcon",
   "Garage",
   "Buanderie",
   "La grotte",
   "Galetas",
   "Terrasse",
   "Véranda",
   "Cheminée",
   "Atelier",
   "Ascenseur",
   "Espace de stockage",
   "Télévision par câble",
   "Connexion RNIS",
   "Convient aux enfants",
   "Accessible aux fauteuils roulants",
   "Animaux acceptés",
   "Construction Minergie",
   "Certifié Minergie",
   "Piscine"
  ],
  [
    "Aussicht",
     "Parkplatz",
     "Balkon",
     "Garage",
     "Allzweckraum",
     "Höhle",
     "Galetas",
     "Terrasse",
     "Veranda",
     "Kamin",
     "Atelier",
     "Aufzug",
     "Lagerraum",
     "Kabelfernsehen",
     "ISDN-Anschluss",
     "Für Kinder geeignet",
     "Behindertengerecht",
     "Haustiere erlaubt",
     "Bau Minergie",
     "Minergie zertifiziert",
     "Schwimmbad"
  ],
  [
    "Vista",
     "Parcheggio",
     "Balcone",
     "Box auto",
     "Stanza utile",
     "Grotta",
     "Galetas",
     "Terrazza",
     "Veranda",
     "Camino",
     "Atelier",
     "Ascensore",
     "Spazio di archiviazione",
     "Tv via cavo",
     "Connessione ISDN",
     "Adatto ai bambini",
     "Accessibile alle sedie a rotelle",
     "Animali ammessi",
     "Construction Minergie",
     "Certificato Minergie",
     "Piscina"  
  ]
];

export const outdoorEquipList = [
  [
    "Elevator",
    "Suitable for animals",
    "Adapted for disabled",
    "Suitable for wheelchair",
    "Funiture",
    "Garden",
    "Crossing",
    "Residential",
    "Calm object",
    "Balcony",
    "Terrace",
    "Separate WC",
    "Hoist",
    "Fireplace",
    "Numerous storage",
    "Cable way",
    "Air conditioner",
    "Divisible",
    "Outside",
    "Terrace",
    "Garden",
    "garden bench",
    "Vegetables",
    "Etang",
    "Common swimming pool",
    "Addiction",
    "Covered parking spaces",
    "Park places",
    "Garage",
    "Box",
    "Box with deposit",
    "In pinion",
    "Terraced house",
    "Private pool"
  ],
  [
    "Ascenseur",
     "Convient aux animaux",
     "Adapté pour les handicapés",
     "Convient aux fauteuils roulants",
     "Mobilier",
     "Jardin",
     "Traversée",
     "Résidentiel",
     "Objet calme",
     "Balcon",
     "Terrasse",
     "WC séparé",
     "Levage",
     "Cheminée",
     "Nombreux rangements",
     "Chemin de câble",
     "Climatisation",
     "Divisible",
     "À l'extérieur",
     "Terrasse",
     "Jardin",
     "Banc de jardin",
     "Des légumes",
     "Etang",
     "Piscine commune",
     "Dépendance",
     "Places de parking couvertes",
     "Places de parc",
     "Garage",
     "Boîte",
     "Boîte avec dépôt",
     "En pignon",
     "Maison mitoyenne",
     "Piscine privée"
  ],
  [
    "Aufzug",
     "Für Tiere geeignet",
     "Angepasst für Behinderte",
     "Rollstuhlgerecht",
     "Funiture",
     "Garten",
     "Kreuzung",
     "Wohn",
     "Ruhiges Objekt",
     "Balkon",
     "Terrasse",
     "Getrenntes WC",
     "Hissen",
     "Kamin",
     "Zahlreiche Speicher",
     "Seilbahn",
     "Klimaanlage",
     "Teilbar",
     "Draußen",
     "Terrasse",
     "Garten",
     "Gartenbank",
     "Gemüse",
     "Etang",
     "Gemeinsames Schwimmbad",
     "Sucht",
     "Überdachte Parkplätze",
     "Parkplätze",
     "Garage",
     "Box",
     "Box mit Kaution",
     "Im Ritzel",
     "Reihenhaus",
     "Privater Pool"
  ],
  [
    "Ascensore",
     "Adatto agli animali",
     "Adattato per disabili",
     "Adatto per sedia a rotelle",
     "Funiture",
     "Giardino",
     "Crossing",
     "Residenziale",
     "Oggetto calmo",
     "Balcone",
     "Terrazza",
     "WC separato",
     "Hoist",
     "Camino",
     "Numerose memorie",
     "Cableway",
     "Condizionatore",
     "Divisibile",
     "Al di fuori",
     "Terrazza",
     "Giardino",
     "panca da giardino",
     "Verdure",
     "Etang",
     "Piscina comune",
     "Dipendenza",
     "Posti auto coperti",
     "Parcheggi",
     "Box auto",
     "Scatola",
     "Scatola con deposito",
     "In pignone",
     "Casa a schiera",
     "Piscina privata"
  ]
];

export const interiorEquipList = [
  [
    "Disabled access",
    "Elevator",
    "No elevator",
    "Pets welcome",
    "No pets allowed",
    "attic",
    "Mezzanine",
    "Visible beams",
    "Furniture",
    "Partially furnished",
    "Unfurnished",
    "Fireplace",
    "Decorative fireplace",
    "Fireplace connection",
    "Swedish stove",
    "Connection for Swedish stove",
    "Ceramic stove",
    "Douche",
    "bath",
    "Separate WC",
    "WC visitors",
    "Sauna",
    "Jacuzzi",
    "Hammam",
    "Fitness room",
    "Common swimming pool",
    "Movie theater",
    "Game room",
    "Dressing",
    "Built-in cabinets",
    "Economat",
    "Winter Garden",
    "Veranda",
    "Cave",
    "Wine cellar",
    "Grenier",
    "Garage",
    "Bike room",
    "Ski room",
    "Abri PC",
    "Reduced",
    "Air conditioner",
    "Simple glazing",
    "Double glazing",
    "Triple glazing",
    "Water softener",
    "Mosquito",
    "Luminous",
    "With stamp",
    "crossing",
    "Open kitchen"
  ],

  [
    "Accès handicapés",
     "Ascenseur",
     "Pas d'ascenseur",
     "Animaux acceptés",
     "Animaux interdits",
     "Grenier",
     "Mezzanine",
     "Faisceaux visibles",
     "Meubles",
     "Partiellement aménagé",
     "Non meublé",
     "Cheminée",
     "Cheminée décorative",
     "Connexion de cheminée",
     "Poêle suédois",
     "Connexion pour cuisinière suédoise",
     "Poêle en céramique",
     "Douche",
     "Une baignoire",
     "WC séparé",
     "Visiteurs de WC",
     "Sauna",
     "Jacuzzi",
     "Hammam",
     "Salle de fitness",
     "Piscine commune",
     "Cinéma",
     "Salle de jeux",
     "Pansement",
     "Armoires encastrées",
     "Economat",
     "Jardin d'hiver",
     "Véranda",
     "La grotte",
     "Cave à vin",
     "Grenier",
     "Garage",
     "Local à vélo",
     "Salle de ski",
     "Abri PC",
     "Réduit",
     "Climatisation",
     "Vitrage simple",
     "Double vitrage",
     "Triple vitrage",
     "Adoucisseur d'eau",
     "Moustique",
     "Lumineux",
     "Avec timbre",
     "Traversée",
     "Cuisine ouverte"
  ],

  [
    "Zugang für Behinderte",
     "Aufzug",
     "Kein Aufzug",
     "Haustiere willkommen",
     "Keine Haustiere erlaubt",
     "Dachboden",
     "Zwischenstock",
     "Sichtbare Strahlen",
     "Möbel",
     "Teilmöbliert",
     "Unmöbliert",
     "Kamin",
     "Dekorativer Kamin",
     "Kaminanschluss",
     "Schwedenofen",
     "Anschluss für Schwedenofen",
     "Keramikofen",
     "Dusche",
     "Bad",
     "Getrenntes WC",
     "WC-Besucher",
     "Sauna",
     "Jacuzzi",
     "Hammam",
     "Fitnessraum",
     "Gemeinsames Schwimmbad",
     "Kino",
     "Spielzimmer",
     "Dressing",
     "Einbauschränke",
     "Economat",
     "Wintergarten",
     "Veranda",
     "Höhle",
     "Weinkeller",
     "Grenier",
     "Garage",
     "Fahrradraum",
     "Skiraum",
     "Abri PC",
     "Reduziert",
     "Klimaanlage",
     "Einfache Verglasung",
     "Doppelverglasung",
     "Dreifachverglasung",
     "Wasserenthärter",
     "Moskito",
     "Leuchtend",
     "Mit Stempel",
     "Kreuzung",
     "Offene Küche"
  ],

  [
    "Accesso disabilitato",
     "Ascensore",
     "Nessun ascensore",
     "Animali ammessi",
     "Non sono ammessi animali",
     "Attico",
     "Soppalco",
     "Travi a vista",
     "Mobilia",
     "Parzialmente arredato",
     "Non arredato",
     "Camino",
     "Camino decorativo",
     "Connessione al camino",
     "Stufa svedese",
     "Collegamento per stufa svedese",
     "Stufa in ceramica",
     "Douche",
     "bagno",
     "WC separato",
     "Visitatori WC",
     "Sauna",
     "Vasca idromassaggio",
     "Hammam",
     "Sala fitness",
     "Piscina comune",
     "Cinema",
     "Sala giochi",
     "Spogliatoio",
     "Armadi a muro",
     "Economat",
     "Giardino d'inverno",
     "Veranda",
     "Grotta",
     "Cantina",
     "Grenier",
     "Box auto",
     "Bike room",
     "Deposito sci",
     "Abri PC",
     "Ridotto",
     "Condizionatore",
     "Vetratura semplice",
     "Doppi vetri",
     "Triplo vetro",
     "Addolcitore",
     "Zanzara",
     "Luminoso",
     "Con timbro",
     "Crossing",
     "Cucina aperta"
  ]
];

export const otherEquipList = [
  [
    "Equipped kitchen",
    "Open kitchen",
    "cooker",
    "Kitchenette",
    "Vitroceramic plates",
    "Induction hobs",
    "Four",
    "Steam oven",
    "Microwave oven",
    "Fridge",
    "Freezer",
    "Dishwasher",
    "Washing machine",
    "Tumble drier",
    "Secom",
    "Private laundry",
    "Laundry room",
    "Central vaccum",
    "Crib",
    "Phone",
    "Fax",
    "Network construction",
    "Satellite",
    "Internet connection",
    "Alarm",
    "Interphone",
    "Digicode",
    "videophone",
    "Camera",
    "guardian",
    "Concierge",
    "Ventilation",
    "Wiring channels",
    "Electric blinds",
    "Automation",
    "Wastewater evacuation"
  ],
  [
    "Cuisine équipée",
    "Cuisine ouverte",
    "Cuisinier",
    "Kitchenette",
    "Plaques vitrocéramiques",
    "Tables de cuisson à induction",
    "Quatre",
    "Four à vapeur",
    "Four micro-onde",
    "Frigo",
    "Congélateur",
    "Lave-vaisselle",
    "Machine à laver",
    "Sèche-linge",
    "Secom",
    "Buanderie privée",
    "Buanderie",
    "Aspirateur central",
    "Lit de bébé",
    "Téléphone",
    "Fax",
    "Construction du réseau",
    "Satellite",
    "Connexion Internet",
    "Alarme",
    "Interphone",
    "Digicode",
    "Vidéophone",
    "Caméra",
    "Gardien",
    "La conciergerie",
    "Ventilation",
    "Canaux de câblage",
     "Stores électriques",
     "Automatisation",
     "Évacuation des eaux usées"
  ],
  [
    "Ausgestattete Küche",
     "Offene Küche",
     "Kocher",
     "Kochnische",
     "Glaskeramikplatten",
     "Induktionskochfelder",
     "Vier",
     "Dampfofen",
     "Mikrowelle",
     "Kühlschrank",
     "Gefrierschrank",
     "Geschirrspülmaschine",
     "Waschmaschine",
     "Trockner",
     "Secom",
     "Private Wäsche",
     "Wäschekammer",
     "Zentralstaubsauger",
     "Krippe",
     "Telefon",
     "Fax",
     "Netzwerkaufbau",
     "Satellit",
     "Internetverbindung",
     "Alarm",
     "Sprechanlage",
     "Digicode",
     "Video Telefon",
     "Kamera",
     "Wächter",
     "Portier",
     "Belüftung",
     "Verdrahtungskanäle",
     "Elektrische Jalousien",
     "Automatisierung",
     "Abwasserentsorgung"
  ],
  [
    "Cucina attrezzata",
     "Cucina aperta",
     "Fornello",
     "Cucinino",
     "Lastre di vetroceramica",
     "Piani cottura a induzione",
     "Quattro",
     "Forno a vapore",
     "Forno a microonde",
     "Frigo",
     "Congelatore",
     "Lavastoviglie",
     "Lavatrice",
     "Asciugatrice",
     "Secom",
     "Lavanderia privata",
     "Lavanderia",
     "Vaccum centrale",
     "Presepe",
     "Telefono",
     "Fax",
     "Costruzione della rete",
     "Satellitare",
     "Connessione internet",
     "Allarme",
     "Citofono",
     "Codice da digitare",
     "video telefono",
     "Telecamera",
     "custode",
     "Concierge",
     "Ventilazione",
     "Canali di cablaggio",
     "Tapparelle elettriche",
     "Automazione",
     "Evacuazione delle acque reflue"
  ]
];

export const soilList = [
  [
    "At choice",
    "Floor tile",
    "Parquet",
    "Mosaic parquet",
    "Old parquet",
    "Laminate",
    "Carpet",
    "Marble",
    "Pierre",
    "Granite"
  ],
  [
    "Au choix",
    "Carrelage",
    "Parquet",
    "Parquet mosaïque",
    "Vieux parquet",
    "Stratifié",
    "Tapis",
    "Marbre",
    "Pierre",
    "Granit"
  ],
  [
    "Nach Wahl",
     "Bodenfliese",
     "Parkett",
     "Mosaikparkett",
     "Altes Parkett",
     "Laminieren",
     "Teppich",
     "Marmor",
     "Pierre",
     "Granit"
  ],
  [
    "A scelta",
     "Piastrella per pavimento",
     "Parquet",
     "Parquet a mosaico",
     "Parquet vecchio",
     "Laminato",
     "Tappeto",
     "Marmo",
     "Pierre",
     "Granito"
  ]
]

export const expositionList = [
  [
    "North",
    "West",
    "South",
    "East"
  ],
  [
    "Nord",
    "Ouest",
    "Sud",
    "Est"
  ],
  [
    "Norden",
     "Westen",
     "Süden",
     "Osten"
  ],
  [
    "Nord",
     "Ovest",
     "Sud",
     "Est"
  ]
]

export const viewsList = [
  [
    "Nice view",
    "clear",
    "impregnable",
    "Panoramic",
    "Lac",
    "More",
    "rural",
    "mountains",
    "Alpes",
    "Jura"
  ],
  [
    "Belle vue",
    "Clair",
    "Imprenable",
    "Panoramique",
    "Lac",
    "Plus",
    "Rural",
    "Les montagnes",
    "Alpes",
    "Jura",
  ], 
  [
    "Schöne Aussicht",
     "klar",
     "uneinnehmbar",
     "Panorama",
     "Lac",
     "Mehr",
     "ländlich",
     "Berge",
     "Alpes",
     "Jura"
  ],
  [
    "Bella vista",
     "chiaro",
     "inespugnabile",
     "Panoramic",
     "Lac",
     "Di Più",
     "rurale",
     "montagne",
     "Alpi",
     "Jura"
  ]
]

export const sunshineList = [
  [
    "Optimal",
    "Favorable",
    "Good",
    "All day",
    "Morning",
    "In the evening"
  ],
  [
    "Optimale",
    "Favorable",
    "Bien",
    "Toute la journée",
    "Matin",
    "Dans la soirée",
  ],
  [
    "Optimal",
     "Günstig",
     "Gut",
     "Den ganzen Tag",
     "Morgen",
     "Abends"
  ],
  [
    "Ottimale",
     "Favorevole",
     "Buono",
     "Tutto il giorno",
     "Mattina",
     "In serata"
  ]
]

export const legalFormList = [
  "Sole proprietorship",
  "Partnership",
  "Foundation",
  "Public limited company(AG)",
  "Limited liability company(GmbH)",
  "Association"
]

export const propertyTypeList = [
  "Select", "Residential", "Commercial", "Mixed use"
]

export const unitsCountList = [
  "Select", "Single family home",1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,"25+"
]

export const unitIdentificationList = [
  "Select", "Numeric(Unit1, Unit2, Unit3)", "Alphabetic(Unit A, Unit B, Unit C)", "Custom"
]

export const buildingAttributesList = [
[  "common Laundry",
  "Fitness room",
  "Swimming pool",
  "Tennis courts",
  "Club house",
  "Gated property",
  "Secured entry",
  "Elevator",
  "On-site manager",
  "Doorman",
  "Yard access"],
  [
    "buanderie commune",
    "Salle de fitness",
    "Piscine",
    "Terrain de tennis",
    "Club house",
    "Propriété fermée",
    "Entrée sécurisée",
    "Ascenseur",
    "Gestionnaire sur site",
    "Portier",
    "Accès au jardin"
  ],
  [
    "gemeinsame Wäsche",
   "Fitnessraum",
   "Schwimmbad",
   "Tennisplätze",
   "Clubhaus",
   "Gated Eigenschaft",
   "Gesicherter Zugang",
   "Aufzug",
   "Vor-Ort-Manager",
   "Türsteher",
   "Zugang zum Hof"
  ],
  [
    "lavanderia comune",
   "Sala fitness",
   "Piscina",
   "Campi da tennis",
   "Club house",
   "Proprietà recintata",
   "Ingresso protetto",
   "Ascensore",
   "Responsabile in loco",
   "Portiere",
   "Accesso all'iarda"

  ]
]

export const correspondenceList = [
  "Email",
  "Post"
]

export const languageList = [
  "Chinese",
  "English",
  "French",
  "German",
  "Italian",
  "Japanese",
  "Portuguese",
  "Spanish"
]
export const tableData = [
  { id: 1, name: 'Chikwa Eligson', postcode: 24, city: 'Lagos', country: 'country-1', phone: '2385', email: 'user@gestimo.com' },
  { id: 2, name: 'Bamidele Johnson', postcode: 18, city: 'Anambra', country: 'country-4', phone: '3328', email: 'user1@gestimo.com' },
  { id: 3, name: 'John Lee', postcode: 20, city: 'Abuja', country: 'country-2', phone: '7896', email: 'user2@gestimo.com' },
  { id: 4, name: 'Binta Pelumi', postcode: 22, city: 'Jos', country: 'country-3', phone: '1236', email: 'user3@gestimo.com' },
  { id: 5, name: 'Cassidy Ferangamo', postcode: 30, city: 'Lagos', country: 'country-4', phone: '5874', email: 'user4@gestimo.com' },
  { id: 6, name: 'Damian Swaggbag', postcode: 35, city: 'PortHarcourt', country: 'country-1', phone: '2365', email: 'user5@gestimo.com' },
  { id: 7, name: 'Loveth Sweetstick', postcode: 20, city: 'Imo', country: 'country-3', phone: '4521', email: 'user6@gestimo.com' },
  { id: 8, name: 'Zzaz Zuzzi', postcode: 19, city: 'Bayelsa', country: 'country-2', phone: '8965', email: 'user7@gestimo.com' },
  { id: 9, name: 'Ian Sweetmouth', postcode: 18, city: 'Enugu', country: 'country-4', phone: '8521', email: 'user8@gestimo.com' },
  { id: 10, name: 'Elekun Bayo', postcode: 21, city: 'Zamfara', country: 'country-4', phone: '3654', email: 'user9@gestimo.com' },
];

export const countryList2 = [
  ["Switzerland", "France"],
  ["Suisse", "France"],
  ["Schweiz", "Frankreich"],
  ["Svizzera", "Francia"]
]

export const cantonsList = [
  // "Aargau", german
  //"Appenzell Ausserrhoden",
  // "Appenzell Innerrhoden",
  // "Basel-Landschaft",
  // "Basel-Stadt ",
  "Bern (BE)",
  "Fribourg (FR)",
  "Genève (GE)",
  // "Glarus",
  // "Graubünden",
  "Jura (JU)",
  // "Luzern",
  "Neuchâtel (NE)",
  // "Nidwalden",
  // "Obwalden",
  // "Schaffhausen",
  // "Schwyz",
  // "Solothurn",
  // "St. Gallen",
  // "Thurgau ",
  // "Ticino",
  // "Uri",
  "VS",
  "VD",
  // "Zug",
  // "Zürich"
]

export const abrList=[
"AG",
"AR",
"AI",
"BL",
"BS",
"BE",
"FR",
"GE",
"GL",
"GR",
"JU",
"LU",
"NE",
"NW",
"OW",
"SH",
"SZ",
"SO",
"SG",
"TG",
"TI",
"UR",
"VS",
"VD",
"ZG",
"ZH"]

export const cityList = [
  // ["Aarau", "Aarburg", "Baden", "Bremgarten (AG)", "Brugg", "Kaiserstuhl (AG)", "Klingnau", "Laufenburg", "Lenzburg", "Mellingen", "Möhlin", "Oftringen", "Rheinfelden", "Spreitenbach", "Suhr", "Wettingen", "Wohlen (AG)", "Zofingen", "Bad Zurzach"],
   // ["Herisau"],
    // ["Appenzell"],
     // ["Aesch (BL)", "Allschwil", "Arlesheim", "Binningen", "Birsfelden", "Laufen (BL)", "Liestal", "Münchenstein", "Muttenz", "Oberwil (BL)", "Pratteln", "Reinach (BL)", "Waldenburg"],
      // ["Basel", "Riehen"],
       ["Aarberg", "Belp", "Bern", "Biel/Bienne", "Büren a.A.", "Burgdorf", "Erlach", "Huttwil", "Interlaken", "Ittigen", "Köniz", "La Neuveville", "Langenthal", "Laupen", "Lyss", "Moutier", "Münchenbuchsee", "Münsingen", "Muri bei Bern", "Nidau", "Ostermundigen", "Spiez", "Steffisburg", "Thun", "Unterseen", "Wangen an der Aare", "Wiedlisbach", "Zollikofen"],
        ["Bulle", "Châtel-Saint-Denis", "Estavayer-le-Lac", "Fribourg", "Gruyères", "La Tour-de-Trême", "Murten", "Romont (FR)", "Rue", "Villars-sur-Glâne"],
         ["Carouge (GE)", "Chêne-Bougeries", "Geneva", "Hermance", "Lancy", "Le Grand-Saconnex", "Meyrin", "Onex", "Plan-les-Ouates", "Thônex", "Vernier", "Versoix", "Veyrier"],
          // ["Glarus", "Glarus Nord*"],
           // ["Arosa", "Chur", "Davos*", "Ilanz", "Maienfeld", "Splügen", "St. Moritz", "Thusis"],
            ["Delémont", "Porrentruy", "Saint-Ursanne"],
             // ["Beromünster", "Ebikon", "Emmen", "Horw", "Kriens", "Lucerne", "Sempach", "Sursee", "Willisau"],
              ["Boudry", "La Chaux-de-Fonds", "Le Landeron", "Le Locle", "Neuchâtel", "Peseux", "Val-de-Travers", "Valangin"],
               // ["Stans"],
                // ["Sarnen"],
                 // ["Neuhausen am Rheinfall", "Neunkirch", "Schaffhausen", "Stein am Rhein"],
                  // ["Arth", "Einsiedeln", "Freienbach", "Lachen (SZ)", "Schwyz"],
                   // ["Grenchen", "Olten", "Solothurn"],
                    // ["Altstätten", "Buchs (SG)", "Flawil", "Gossau (SG)", "Lichtensteig", "Rapperswil-Jona", "Rheineck", "Rorschach", "Sargans", "St. Gallen", "Uznach", "Uzwil", "Walenstadt", "Werdenberg", "Wil (SG)"],
                     // ["Amriswil", "Arbon", "Bischofszell", "Diessenhofen", "Frauenfeld", "Kreuzlingen", "Romanshorn", "Steckborn", "Weinfelden"],
                      // ["Agno", "Ascona", "Bellinzona", "Biasca", "Chiasso", "Croglio", "Gordola", "Locarno", "Losone", "Lugano", "Mendrisio", "Morcote", "Riva San Vitale"],
                       // ["Altdorf (UR)"],
                        ["Bourg-Saint-Pierre", "Brig-Glis", "Conthey", "Leuk", "Martigny", "Monthey", "Orsières", "Saillon", "Saint-Maurice", "Sembrancher", "Sierre", "Sion", "Visp", "Zermatt"],
                         ["Aigle", "Aubonne", "Avenches", "Bussigny", "Coppet", "Cossonay", "Crissier", "Cudrefin", "Cully", "Échallens", "Ecublens (VD)", "Gland", "Grandcour", "Grandson", "La Sarraz", "La Tour-de-Peilz", "Lausanne", "Les Clées", "Lutry", "Montreux", "Morges", "Moudon", "Nyon", "Orbe", "Payerne", "Prilly", "Pully", "Renens (VD)", "Rolle", "Vevey", "Saint-Prex", "Vevey", "Villeneuve", "Yverdon-les-Bains"],
                          // ["Baar", "Cham", "Risch", "Steinhausen", "Zug"],
                           // ["Adliswil", "Affoltern am Albis", "Bassersdorf", "Bülach", "Dietikon", "Dübendorf", "Eglisau", "Elgg", "Greifensee", "Grüningen", "Hinwil", "Horgen", "Illnau-Effretikon", "Kloten", "Küsnacht (ZH)", "Männedorf", "Meilen", "Opfikon", "Pfäffikon", "Regensberg", "Regensdorf", "Rheinau", "Richterswil", "Rüti (ZH)", "Schlieren", "Stäfa", "Thalwil", "Urdorf", "Uster", "Wallisellen", "Wädenswil", "Wallisellen", "Wetzikon (ZH)", "Winterthur", "Zollikon"]
                          ]


export const frCantonList = ["Île-de-France", "Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Brittany", "Centre-Val de Loire", "Corsica", "French Guiana", "Grand Est", "Guadeloupe", "Hauts-de-France", "Martinique", "Normandy", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur", "Réunion"]
export const frCityList = [["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil", "Nanterre", "Vitry-sur-Seine", "Créteil", "Asnières-sur-Seine", "Courbevoie", "Versailles", "Colombes", "Aulnay-sous-Bois", "Rueil-Malmaison", "Aubervilliers", "Champigny-sur-Marne", "Saint-Maur-des-Fossés", "Drancy", "Issy-les-Moulineaux","Levallois-Perret","Noisy-le-Grand","Neuilly-sur-Seine"], ["Lyon", "Saint-Étienne", "Grenoble", "Villeurbanne", "Clermont-Ferrand", "Valence", "Vénissieux", "Chambéry", "Annecy", "Vaulx-en-Velin", "Saint-Priest", "Caluire-et-Cuire", "Bourg-en-Bresse", "Bron", "Saint-Martin-d'Hères", "Montluçon", "Montélimar", "Villefranche-sur-Saône", "Échirolles","Roanne","Saint-Chamond","Thonon-les-Bains"], ["Dijon", "Besançon", "Belfort", "Chalon-sur-Saône", "Auxerre", "Nevers", "Mâcon", "Montbéliard", "Sens", "Dole", "Le Creusot", "Beaune"], ["Rennes", "Brest", "Quimper", "Lorient", "Vannes", "Saint-Brieuc", "Saint-Malo", "Lanester"], ["Tours", "Orléans", "Bourges", "Blois", "Châteauroux", "Chartres", "Joué-lès-Tours", "Dreux", "Vierzon", "Fleury-les-Aubrais"], ["Ajaccio", "Bastia"], ["Cayenne", "Saint-Laurent-du-Maroni", "Matoury", "Kourou"], ["Strasbourg", "Reims", "Metz", "Mulhouse", "Nancy", "Colmar", "Troyes", "Charleville-Mézières", "Châlons-en-Champagne", "Thionville", "Haguenau", "Épinal", "Schiltigheim", "Vandoeuvre-lès-Nancy", "Illkirch-Graffenstaden", "Saint-Dizier", "Épernay", "Chaumont", "Montigny-lès-Metz","Forbach","Sarreguemines","Saint-Dié-des-Vosges"], ["Les Abymes", "Baie-Mahault", "Le Gosier", "Sainte-Anne", "Petit-Bourg", "Le Moule", "Sainte-Rose"], ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkirk", "Calais", "Villeneuve-d'Ascq", "Saint-Quentin", "Beauvais", "Valenciennes", "Boulogne-sur-Mer", "Wattrelos", "Douai", "Arras", "Compiègne", "Marcq-en-Barœul", "Creil", "Cambrai", "Lens","Liévin","Maubeuge","Lambersart"], ["Fort-de-France", "Le Lamentin", "Le Robert"], ["Le Havre", "Rouen", "Caen", "Évreux", "Cherbourg-Octeville", "Dieppe", "Saint-Étienne-du-Rouvray", "Sotteville-lès-Rouen", "Alençon", "Le Grand-Quevilly", "Vernon", "Le Petit-Quevilly", "Hérouville-Saint-Clair", "Lisieux"], ["Bordeaux", "Limoges", "Poitiers", "Pau", "La Rochelle", "Mérignac", "Pessac", "Niort", "Bayonne", "Brive-la-Gaillarde", "Angoulême", "Talence", "Anglet", "Agen", "Mont-de-Marsan", "Châtellerault", "Villenave-d'Ornon", "Périgueux", "Saint-Médard-en-Jalles","Bergerac","Bègles","Saintes"], ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers", "Montauban", "Narbonne", "Albi", "Carcassonne", "Sète", "Castres", "Tarbes", "Alès", "Colomiers", "Tournefeuille", "Agde", "Lunel", "Muret", "Rodez","Blagnac","Frontignan","Millau"], ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "Cholet", "La Roche-sur-Yon", "Laval", "Saint-Herblain", "Rezé", "Saumur", "Saint-Sébastien-sur-Loire", "Orvault", "Vertou"], ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon", "Antibes", "Cannes", "La Seyne-sur-Mer", "Hyères", "Fréjus", "Arles", "Grasse", "Martigues", "Cagnes-sur-Mer", "Aubagne", "Salon-de-Provence", "Le Cannet", "Istres", "Gap","Draguignan","La Ciotat","Vitrolles"], ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Le Tampon", "Saint-André", "Saint-Louis", "Saint-Joseph", "Saint-Benoît", "Le Port", "Saint-Leu", "Sainte-Marie", "La Possession", "Sainte-Suzanne"]]


export const contactCategoryList = [
  "Landlord",
  "Customer",
  "Suppliers",
  "Partner"
]

