const language = [
  //English
  {
    app_title: "Gestimmo",
    step1: 'Step 1',
    main_info: 'Main Information',
    title_of_ad: 'Title of Ad',
    description: 'Description',
    country: 'Country',
    postcode: 'Postcode',
    street_and_house_number: 'Street and House number',
    details: 'Details',
    type_of_ownership: 'Type of Ownership',
    for_rent: 'For rent',
    for_sale: 'For sale',
    category: 'Category',
    surface: 'Surface',
    floor: 'Floor',
    rooms: 'Rooms',
    invalid_date_format: 'Invalid Date Format',
    price_type: 'Price Type',
    on_request: 'On request',
    price: 'Price',
    back: 'Back',
    next: 'Next',
    step2: 'Step 2: Extra Details',
    near: 'Near',
    proximity: 'Proximity',
    facilities: 'Facilities',
    outdoor_equipment: 'Outdoor Equipment',
    interior_equipment: 'Interior Equipment',
    other_equipment: 'Other Equipment',
    soils: 'Soils',
    exposition: 'Exposition',
    views: 'Views',
    sunshine: 'Sunshine',    
    step3: 'Step 3: Photos',
    drop_some_files_here: 'Drop some files here!',
    or: 'or',
    choose: 'Choose',
    step4: 'Step 4: Contact Information',
    full_name: 'Full Name',
    phone_number: 'Phone',
    email: 'Email',
    compleated_all_the_steps: 'You have completed all the steps!',
    upload_ads: 'Upload Ads',
    confirm: 'Confirm',
    you_can_continue_from_the_previous_state: 'You can continue from the previous state',
    yes: 'Yes',
    no: 'No',
    result: 'Result',
    load_more: 'Load more',
    type: 'Type',
    rent: 'Rent',
    buy: 'Buy',
    property: 'Property',
    city: 'City',
    floor: 'Floor',
    min: 'Min',
    max: 'Max',
    room: 'Room',
    canton: "Canton",
    availability: "Availability",
    from_date: "From Date",
    immediately: "Immediately",
    charge: "Charge",
    choose: "Choose",
    upload_changes: "Upload Changes",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Canton',
    profile: 'Profile',
    company:'Company',
    create_company:'create company',
    adress:'Address',
    basic_information:'Basic information',
    company_name:'Company name',
    additional_address:'Additional Address',
    inbox_email:'Inbox email address',
    short_name:'Short name for Inbox email address',
    additional_information:'Additional information',
    contact_information:'Contact Information',
    mobile_p:'Mobile phone',
    website:'Website',
    fax:'Fax',
    save_changes:'Save Changes',
    contacts:'Contacts',
    imp_exp:'Import/Export',
    new_contact:'New Contact',
    all:'All',
    filter:'Filter',
    marked:'Marked as deleted',
    attributes:'Attributes',
    b_atributes:'Building Attributes(optional)',
    more_photos:'More Photos',
    create_button:'Create',
    upload_txt:'Upload building photos here. If your building has multiple units, individual unit photos should be added at unit level(later step).',
    photo_property:'Property Photo',
    property_type:'Property Type',
    number_of_units:'Number of units you own',
    unit_identification:'Unit identification',
    add_new_property:'Add new property',
    my_property:'My Properties',
    change_photo:'Change profile photo ',
    master_data:'Master data',
    contact_no:'Contact no.',
    contact_type:'Contact type',
    private:'Private',
    contant_partner:'Contact partner',
    owner:'Owner',
    correspondence_type:'Correspondence type',
    remarks:'Remarks',
    sector:'Sector',
    more_c_information:'More contact information',
    number_of_employes:'Number of employees',
    comercial_register:'Commercial Register no.',
    vat_n:'VAT no.',
    vat_reg:'VAT Reg No',
    phone_number2:'Phone 2',
    name_sufix:'Name suffix',
    cancel:"Cancel",
    me:'Me',
    create_ads:'Create Ads',
    my_ads:'My Ads',
    property:'Property',
    contacts:'Contacts',
    sign_out:'Sign out',
    search:'Search',
    //9/19/2019
    extras: "Extras",
    date: "Date",
    zone: "Zone",
    total: "Total",
    loyer: "Loyer",
    call_up_the_advertiser: "Call up the advertiser",
    information_for_visit: "Information For Visit",
    contact_advertiser: "Contact Advertiser",
    message: "Message",
    send: "Send",
    confirm_dialog: "Confirm Dialog",
    are_you_sure_to_delete: "Are you sure to delete?",
    visitor_comment: "Visitor Comment",
    agency_name_is_not_provided: "Agency name is not provided",
    advertiser_name_is_not_provided: "Advertiser name is not provided",
    advertiser_email_is_not_provided: "Advertiser email is not provided",
    visit_name_is_not_provided: "Visit name is not provided",
    visit_phone_is_not_provided: "Visit phone is not provided",
    visit_email_is_not_provided: "Visit email is not provided",
    visit_remark_is_not_provided: "Visit remark is not provided",
    find_your_property: "Find your property",
    work_with_us: "Work With Us",
    divide_details: "Divide details about your product or agency work into parts. a few lines about each one and contact us about any further collaboration. We will respond get back to you in a couple of hours.",
    your_name: "Your Name",
    your_agency: "Your Agency",
    your_email: "Your Email",
    your_message: "Your Message",

    temp_sale: "Currently we have 189 properties for sale",
    temp_rent: "Currently we have 365 properties for rent",

    visit_name: "Visit name",
    visit_email: "Visit email",
    visit_phone: "Visit phone",
    mand_name: "Representative Name",
    mand_email: "Representative Email",
    mand_phone: "Representative Phone"
    
  },
  //French
  {
    app_title: "Gestimmo",
    step1: 'Étape 1',
    main_info: 'Informations principales',
    title_of_ad: "Titre de l'annonce",
    description: 'Description...',
    country: 'Pays',
    postcode: 'NPA',
    street_and_house_number: 'Rue et numéro de maison',
    details: 'Détails',
    type_of_ownership: 'Type de propriété',
    for_rent: 'A louer',
    for_sale: 'À vendre',
    category: 'Catégorie',
    surface: 'Surface',
    floor: 'Sol',
    rooms: 'Pièces',
    invalid_date_format: 'Format de date invalide',
    price_type: 'Type de prix',
    on_request: 'Sur demande',
    price: 'Prix',
    back: 'Retour',
    next: 'Prochain',
    step2: 'Étape 2: Détails supplémentaires',
    near: 'Près',
    proximity: 'Proximité',
    facilities: 'Installations',
    outdoor_equipment: 'Équipement de plein air',
    interior_equipment: 'Équipement intérieur',
    other_equipment: 'Autre équipement',
    soils: 'Les sols',
    exposition: 'Exposition',
    views: 'Des vues',
    sunshine: 'Ensoleillement',    
    step3: 'Étape 3: Photos',
    drop_some_files_here: 'Déposer des fichiers ici!',
    or: 'ou',
    choose: 'Choisir',
    step4: 'Étape 4: Coordonnées',
    full_name: 'Nom complet',
    phone_number: 'Téléphone',
    email: 'Email',
    compleated_all_the_steps: 'Vous avez terminé toutes les étapes!',
    upload_ads: 'Transférer des annonces',
    confirm: 'Confirmer',
    you_can_continue_from_the_previous_state: 'Vous pouvez continuer à partir de l n\'état précédent',
    yes: 'Oui',
    no: 'Non',
    result: 'résultat',
    load_more: 'Charger plus',
    type: 'Type',
    rent: 'Louer',
    buy: 'Acheter',
    property: 'Propriété',
    city: 'Localité',
    floor: 'Étage',
    min: 'Min',
    max: 'Max',
    room: 'Pièce',
    canton: "Canton",
    availability: "Disponibilité",
    from_date: "Partir de la date",
    immediately: "Immédiatement",
    charge: "Charge",
    choose: "Choisir",
    upload_changes: "Transférer les modifications",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Canton',
    profile: 'Profil',
    company:'Entreprise',
    create_company:'créer une entreprise',
    adress:'Adresse',
    basic_information:'Informations de base',
    company_name:'Nom de la compagnie',
    additional_address:'Adresse additionnelle',
    inbox_email:'Adresse email de la boîte de réception',
    short_name:"Nom abrégé de l'adresse électronique de la boîte de réception",
    additional_information:'Informations supplémentaires',
    contact_information:'Coordonnées',
    mobile_p:'Téléphone portable',
    website:'Site web',
    fax:'fax',
    save_changes:'Sauvegarder les modifications',
    contacts:'Contacts',
    imp_exp:'Importation/Exportation',
    new_contact:'Nouveau contact',
    all:'Tous',
    filter:'Filtrer ',
    marked:'Marqué comme supprimé',
    attributes:'Attributs',
    b_atributes:'Attributs de construction (facultatif)',
    more_photos:'Plus de photos',
    create_button:'Créer',
    upload_txt:"Téléchargez les photos du bâtiment ici. Si votre bâtiment comporte plusieurs unités, vous devez ajouter une unité individuelle au niveau de l'unité (étape ultérieure).",
    photo_property:'Photo de la propriété',
    property_type:'Type de propriété',
    number_of_units:"Nombre d'unités que vous possédez",
    unit_identification:"Identification de l'unité",
    add_new_property:'Ajouter nouvelle propriété',
    my_property:'Mes propriétés',
    change_photo:' Modifier image du profil ',
    master_data:' Données de base ',
    contact_no:'Nº du contact',
    contact_type:'Type de contact',
    private:'Privé',
    contant_partner:'Interlocuteur ',
    owner:'Propriétaire',
    correspondence_type:'Voie de correspondance type',
    remarks:'Remarques',
    sector:'Secteur',
    more_c_information:'Autres informations de contact',
    number_of_employes:'Nombre de collaborateurs',
    comercial_register:"Nº d'immatriculation au registre du commerce",
    vat_n:'Nº de TVA',
    vat_reg:' Nº d’identification TVA',
    phone_number2:'Phone 2',
    name_sufix:'Complément',
    cancel:"Annuler",
    save:"Enregistrer",
    me:'Moi',
    create_ads:'Créer des annonces',
    my_ads:'Mes annonces',
    property:'Propriété',
    contacts:'Contacts',
    sign_out:'Déconnexion',
    search:'Chercher',
    //9/19/2019
    extras: "Suppléments",
    date: "Date",
    zone: "Zone",
    total: "Total",
    loyer: "Loyer",
    call_up_the_advertiser: "Appeler l'annonceur",
    information_for_visit: "Informations pour la visite",
    contact_advertiser: "Contact annonceur",
    message: "Message",
    send: "Envoyer",
    confirm_dialog: "Confirmer le dialogue",
    are_you_sure_to_delete: "Êtes-vous sûr de vouloir supprimer?",
    visitor_comment: "Commentaire du visiteur",
    agency_name_is_not_provided: "Le nom de l'agence n'est pas fourni",
    advertiser_name_is_not_provided: "Le nom de l'annonceur n'est pas fourni",
    advertiser_email_is_not_provided: "L'adresse email de l'annonceur n'est pas fournie",
    visit_name_is_not_provided: "Le nom de la visite n'est pas fourni",
    visit_phone_is_not_provided: "Le téléphone de visite n'est pas fourni",
    visit_email_is_not_provided: "L'email de visite n'est pas fourni",
    visit_remark_is_not_provided: "La remarque de visite n'est pas fournie",
    find_your_property: "Trouvez votre propriété",
    work_with_us: "Travaille avec nous",
    divide_details: "Divisez les détails concernant votre produit ou votre travail en agence en plusieurs parties. Quelques lignes sur chacun et contactez-nous pour toute collaboration ultérieure. Nous vous répondrons dans quelques heures.",
    your_name: "Votre nom",
    your_agency: "Votre agence",
    your_email: "Votre email",
    your_message: "Votre message",

    temp_sale: "Actuellement nous avons 189 biens à la vente",
    temp_rent: "Actuellement nous avons 365 biens à louer",


    visit_name: "Nom de la visite",
    visit_email: "Email de visite",
    visit_phone: "Visiter le téléphone",
    mand_name: "Nom de la mandataire",
    mand_email: "Email de mandataire",
    mand_phone: "Mandataire téléphone"


  },

  //german
  {
    app_title: "Gestimmo",
    step1: 'Schritt 1',
    main_info: 'Hauptinformation',
    title_of_ad: 'Anzeigentitel',
    description: 'Beschreibung',
    country: 'Land',
    postcode:'Postleitzahl',
    postcode_and_city: 'Postleitzahl',
    street_and_house_number: 'Straße und Hausnummer',
    details: 'Einzelheiten',
    type_of_ownership: 'Art des Eigentums',
    for_rent: 'Zu vermieten',
    for_sale: 'Zu verkaufen',
    category: 'Kategorie',
    surface: 'Oberfläche',
    floor: 'Fußboden',
    rooms: 'Räume',
    invalid_date_format: 'Ungültiges Datumsformat',
    price_type: 'Preistyp',
    on_request: 'Auf Anfrage',
    price: 'Preis',
    back: 'Zurück',
    next: 'Nächster',
    step2: 'Schritt 2: Zusätzliche Details',
    near: 'Nahe',
    proximity: 'Nähe',
    facilities: 'Anlagen',
    outdoor_equipment: 'Outdoor Ausrüstung',
    interior_equipment: 'Innenausstattung',
    other_equipment: 'Andere Ausrüstung',
    soils: 'Böden',
    exposition: 'Exposition',
    views: 'Ansichten',
    sunshine: 'Sonnenschein',    
    step3: 'Schritt 3: Fotos',
    drop_some_files_here: 'Legen Sie einige Dateien hier ab!',
    or: 'oder',
    choose: 'Wählen',
    step4: 'Schritt 4: Kontaktinformationen',
    full_name: 'Vollständiger Name',
    phone_number: 'Telefonnummer',
    email: 'Email',
    compleated_all_the_steps: 'Sie haben alle Schritte abgeschlossen!',
    upload_ads: 'Anzeigen hochladen',
    confirm: 'Bestätigen',
    you_can_continue_from_the_previous_state: 'Sie können mit dem vorherigen Status fortfahren',
    yes: 'Ja',
    no: 'Nein',
    result: 'Ergebnis',
    load_more: 'Mehr laden',
    type: 'Art',
    rent: 'Miete',
    buy: 'Kaufen',
    property: 'Eigentum',
    city: 'Stadt',
    floor: 'Fußboden',
    min: 'Mindest',
    max: 'Max',
    room: 'Zimmer',
    canton: "Kanton",
    availability: "Verfügbarkeit",
    from_date: "Ab Datum",
    immediately: "Sofort",
    charge: "Aufladen",
    choose: "Wählen",
    upload_changes: "Änderungen hochladen",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Kanton',
    profile: 'Profil',
    company:'Firma',
    create_company:'Firma gründen',
    adress:'Adresse',
    basic_information:'Grundinformation',
    company_name:'Name der Firma',
    additional_address:'zusätzliche Adresse',
    inbox_email:'E-Mail-Adresse des Posteingangs',
    short_name:'Kurzname für die E-Mail-Adresse des Posteingangs',
    additional_information:'Zusatzinformationen',
    contact_information:'Kontaktinformationen',
    mobile_p:'Mobile',
    website:'Webseite',
    fax:'Fax',
    save_changes:'Änderungen speichern',
    contacts:'Kontakte',
    imp_exp:'Import/Export',
    new_contact:'Neuer Kontakt',
    all:'Alle',
    filter:'Filtern',
    marked:'Als gelöscht markiert',
    attributes:'Attribute',
    b_atributes:'Gebäudeattribute (optional)',
    more_photos:'Weitere Fotos',
    create_button:'Schaffen',
    upload_txt:'Laden Sie hier Gebäudefotos hoch. Wenn Ihr Gebäude über mehrere Einheiten verfügt, sollten einzelne Einheitenfotos zur Einheitenebene hinzugefügt werden (späterer Schritt).',
    photo_property:'Eigentum Foto',
    property_type:'Art der Eigentum',
    number_of_units:'Anzahl der Einheiten, die Sie besitzen',
    unit_identification:'Geräteidentifikation',
    add_new_property:'Neue Eigenschaft hinzufügen',
    my_property:'Meine Eigenschaften',
    change_photo:'Profilbild ändern',

    master_data:' Stammdaten ',
    contact_no:'Kontakt Nr.',
    contact_type:'Kontaktart',
    private:'Privat',
    contant_partner:'Ansprechpartner ',
    owner:'Eigentümer',
    correspondence_type:'Korrespondenzweg',
    remarks:'Bemerkungen',
    sector:'Branche',
    more_c_information:' Weitere Kontaktinformationen ',
    number_of_employes:'Anzahl Mitarbeiter',
    comercial_register:'Handelsregister Nr.',
    vat_n:'MWST Nr.',
    vat_reg:'USt-IdNr.',
    phone_number2:'Telefonnummer 2',
    name_sufix:'Zusatz',
    cancel:"Stornieren",
    save:"Speichern",
    me:'Mich',
    create_ads:'Anzeigen erstellen',
    my_ads:'Meine Anzeigen',
    property:'Eigentum',
    contacts:'Kontakte',
    sign_out:'Ausloggen',
    search:'Suche',
    //9/19/2019
    extras: "Extras",
    date: "Datum",
    zone: "Zone",
    total: "Gesamt",
    loyer: "Loyer",
    call_up_the_advertiser: "Rufen Sie den Inserenten an",
    information_for_visit: "Informationen zum Besuch",
    contact_advertiser: "Wenden Sie sich an den Werbetreibenden",
    message: "Botschaft",
    send: "Senden",
    confirm_dialog: "Bestätigen Sie den Dialog",
    are_you_sure_to_delete: "Bist du sicher, das du das löschen möchtest?",
    visitor_comment: "Besucherkommentar",
    agency_name_is_not_provided: "Der Agenturname wird nicht angegeben",
    advertiser_name_is_not_provided: "Der Name des Werbetreibenden wird nicht angegeben",
    advertiser_email_is_not_provided: "Die E-Mail-Adresse des Werbetreibenden wird nicht angegeben",
    visit_name_is_not_provided: "Der Name des Besuchs wird nicht angegeben",
    visit_phone_is_not_provided: "Ein Besuchstelefon ist nicht vorgesehen",
    visit_email_is_not_provided: "Eine Besuchs-E-Mail wird nicht bereitgestellt",
    visit_remark_is_not_provided: "Besuch Bemerkung ist nicht vorgesehen",
    find_your_property: "Finden Sie Ihre Immobilie",
    work_with_us: "Arbeite mit uns",
    divide_details: "Teilen Sie Details zu Ihrem Produkt oder Ihrer Agenturarbeit in Teile auf. ein paar Zeilen über jeden und kontaktieren Sie uns für weitere Zusammenarbeit. Wir werden uns in ein paar Stunden bei Ihnen melden.",
    your_name: "Dein Name",
    your_agency: "Ihre Agentur",
    your_email: "Deine E-Mail",
    your_message: "Deine Nachricht",

    temp_sale: "Derzeit stehen 189 Immobilien zum Verkauf",
    temp_rent: "Derzeit stehen 365 Immobilien zur Miete",

    visit_name: "Name des Besuchs",
    visit_email: "Besuchen Sie E-Mail",
    visit_phone: "Besuchen Sie Telefon",
    mand_name: "Name des Attorney",
    mand_email: "Attorney Sie E-Mail",
    mand_phone: "Attorney des Attorney"

  },

  //italian
  {
    app_title: "Gestimmo",
    step1: 'Passaggio 1',
    main_info: 'Informazione principale',
    title_of_ad: 'Titolo dell\'annuncio',
    description: 'Descrizione',
    country: 'Nazione',
    postcode: 'codice postale',
    street_and_house_number: 'Via e numero civico',
    details: 'Dettagli',
    type_of_ownership: 'Tipo di proprietà',
    for_rent: 'Da affittare',
    for_sale: 'In vendita',
    category: 'Categoria',
    surface: 'Superficie',
    floor: 'Pavimento',
    rooms: 'Camere',
    invalid_date_format: 'Formato data non valido',
    price_type: 'Tipo di prezzo',
    on_request: 'Su richiesta',
    price: 'Prezzo',
    back: 'Indietro',
    next: 'Il prossimo',
    step2: 'Passaggio 2: dettagli aggiuntivi',
    near: 'Vicino',
    proximity: 'Prossimità',
    facilities: 'Strutture',
    outdoor_equipment: 'Attrezzature da esterno',
    interior_equipment: 'Equipaggiamento interno',
    other_equipment: 'Altro equipaggiamento',
    soils: 'Suoli',
    exposition: 'Esposizione',
    views: 'Visualizzazioni',
    sunshine: 'Luce del sole',    
    step3: 'Passaggio 3: foto',
    drop_some_files_here: 'Rilascia alcuni file qui!',
    or: 'o',
    choose: 'Scegliere',
    step4: 'Passaggio 4: informazioni di contatto',
    full_name: 'Nome e cognome',
    phone_number: 'Numero di telefono',
    email: 'E-mail',
    compleated_all_the_steps: 'Hai completato tutti i passaggi!',
    upload_ads: 'Carica annunci',
    confirm: 'Confermare',
    you_can_continue_from_the_previous_state: 'Puoi continuare dallo stato precedente',
    yes: 'Si',
    no: 'No',
    result: 'Risultato',
    load_more: 'Carica di più',
    type: 'Genere',
    rent: 'Affitto',
    buy: 'Acquistare',
    property: 'Proprietà',
    city: 'Città',
    floor: 'Pavimento',
    min: 'Min',
    max: 'Max',
    room: 'Camera',
    canton: "Cantone",
    availability: "Disponibilità",
    from_date: "Dalla data",
    immediately: "Subito",
    charge: "Carica",
    choose: "Scegliere",
    upload_changes: "Carica modifiche",
    english_native: 'English',  
    french_native: 'Français',
    german_native: 'Deutsch',
    italian_native: 'Italiano',
    canton: 'Cantone',
    profile: 'Profilo',
    company:'Ditta',
    create_company:'creare società',
    adress:'Indirizzo',
    basic_information:'Informazioni di base',
    company_name:'Ditta',
    additional_address:'Indirizzo aggiuntivo',
    inbox_email:'Indirizzo email in arrivo',
    short_name:"Nome breve per l'indirizzo e-mail in arrivo",
    additional_information:'Ulteriori informazioni ',
    contact_information:'Informazioni di contatto',
    mobile_p:'Cellulare',
    website:'Sito web',
    fax:'Fax',
    save_changes:'Salva I Cambiamenti',
    contacts:'Contatti',
    imp_exp:'Importa/Esporta',
    new_contact:'Nuovo contatto',
    all:'Tutti',
    filter:'Filtra',
    marked:'Contrassegnato come eliminato',
    attributes:'Attributi',
    b_atributes:'Attributi di costruzione (facoltativo)',
    more_photos:'Altre foto',
    create_button:'Create',
    upload_txt:"Carica qui le foto degli edifici. Se l'edificio ha più unità, le foto delle singole unità devono essere aggiunte a livello di unità (passaggio successivo).",
    photo_property:'Foto della proprietà',
    property_type:'Tipo di proprietà',
    number_of_units:'Numero di unità che possiedi',
    unit_identification:"Identificazione dell'unità",
    add_new_property:'Aggiungi nuova proprietà',
    my_property:'Le mie proprietà',
    change_photo:'Cambia immagine del profilo ',

    master_data:' Dati anagrafici ',
    contact_no:'Contatto n.',
    contact_type:'Tipo di contatto',
    private:'Privato',
    contant_partner:' Persona di contatto ',
    owner:'Titolare',
    correspondence_type:'Corrispondenza',
    remarks:'Osservazioni',
    sector:'Settore',
    more_c_information:' Altre informazioni di contatto ',
    number_of_employes:'Numero di dipendenti',
    comercial_register:'Numero Registro di commercio',
    vat_n:'N. IVA',
    vat_reg:'N. IVA',
    phone_number2:'Telefono 2',
    name_sufix:'Aggiunta',
    cancel:"Annulla",
    save:'Salvare',
    me:'Me',
    create_ads:'Crea annunci',
    my_ads:'"I miei annunci',
    property:'Proprietà',
    contacts:'Contatti',
    sign_out:'Disconnessione',
    search:'Ricerca',
    //9/19/2019
    extras: "Extra",
    date: "Data",
    zone: "Zona",
    total: "Totale",
    loyer: "Loyer",
    call_up_the_advertiser: "Chiama l'inserzionista",
    information_for_visit: "Informazioni per la visita",
    contact_advertiser: "Contatta l'inserzionista",
    message: "Messaggio",
    send: "Spedire",
    confirm_dialog: "Conferma finestra di dialogo",
    are_you_sure_to_delete: "Sei sicuro di cancellare?",
    visitor_comment: "Commento del visitatore",
    agency_name_is_not_provided: "Il nome dell'agenzia non è fornito",
    advertiser_name_is_not_provided: "Il nome dell'inserzionista non è fornito",
    advertiser_email_is_not_provided: "L'email dell'inserzionista non è fornita",
    visit_name_is_not_provided: "Il nome della visita non è fornito",
    visit_phone_is_not_provided: "Il telefono visita non è fornito",
    visit_email_is_not_provided: "L'email di visita non è fornita",
    visit_remark_is_not_provided: "L'osservazione della visita non è fornita",
    find_your_property: "Trova la tua proprietà",
    work_with_us: "Lavora con noi",
    divide_details: "Dividi i dettagli relativi al tuo prodotto o all'agenzia in parti. alcune righe su ciascuno di essi e contattaci per qualsiasi ulteriore collaborazione. Ti risponderemo entro un paio d'ore.",
    your_name: "Il tuo nome",
    your_agency: "La tua agenzia",
    your_email: "La tua email",
    your_message: "Il tuo messaggio",

    temp_sale: "Al momento disponiamo di 189 immobili in vendita",
    temp_rent: "Attualmente disponiamo di 365 immobili in affitto",

    visit_name: "Visita il nome",
    visit_email: "Visita l'e-mail",
    visit_phone: "Visita il telefono",
    mand_name: "procuratore Nome",
    mand_email: "procuratore Email",
    mand_phone: "procuratore Telefonico"

  },
];

export default language;